/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'fibonacci' 
 * Target:  'STM32F407 Flash' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* Keil::Compiler&ARM Compiler:I/O:STDOUT&User@1.2.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
#define RTE_Compiler_IO_STDOUT_User     /* Compiler I/O: STDOUT User */
/* Keil::Compiler&ARM Compiler:I/O:TTY&User@1.2.0 */
#define RTE_Compiler_IO_TTY             /* Compiler I/O: TTY */
#define RTE_Compiler_IO_TTY_User        /* Compiler I/O: TTY User */


#endif /* RTE_COMPONENTS_H */
